/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnnouncementId = IDL.Nat;
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'body' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [Announcement], []),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [IDL.Bool], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnnouncementId = IDL.Nat;
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'body' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [Announcement], []),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [IDL.Bool], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };